CREATE DATABASE IF NOT EXISTS zhunong DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'zhunong'@'%' IDENTIFIED BY 'zhunong123';
GRANT ALL PRIVILEGES ON zhunong.* TO 'zhunong'@'%';
FLUSH PRIVILEGES;
SET GLOBAL time_zone = '+8:00';
